const data = [
  {
    id: 1,
    image:
      "/images/product-images/Brand_New_Fresenius_4008S_Classix_(BP-Model).jpg",
    description: "",
    brand: "",
    area: "featured",
    category: "Hemodialysis",
    name: "Refurbished Fresenius 4008S Classix (BP Model)",
    features: [
      "Dimension: 1370 x 500 x 650mm (H x W x D) (Including shunt interlock and pedestal) approx.",
      "Weight: 86kg",
      "Inlet Pressure: 1.5 to 6.0 bar (Water)",
      "Power Supply: 10 O 240V AC, 50 to 60 Hz",
      "Blood Flow Range: 15 to 600mL/min",
      "Data acquisition and management tool.",
    ],
  },
  {
    id: 34,
    image: "/images/product-images/nikkisosss.jpg",
    description: "",
    brand: "",
    area: "featured",
    category: "Hemodialysis",
    name: "Refurbished Nikkiso DBB-07",
    features: [
      "Consistently high treatment quality",
      "DIASCAN quality control tool Conductivity- based and flow-rate controlled concentrate dosing Disinfection log",
      "BICART cartridge holder Syringe pump",
      "U9000 Ultrafilter and BPM Option",
      "Alarm history",
    ],
  },
  {
    id: 3,
    image: "/images/product-images/water_treatment_plant.jpeg",
    description: "",
    brand: "",
    area: "featured",
    category: "Hemodialysis",
    name: "Water Treatment Plant",
    features: [
      "This WRO System supplies 12 dialysis machines.",
      "Number of membranes: 10 pcs",
      "Model of use: indirect feeding Items included: 1uint UV Light,1unit Permeate Tank, Capacity(1500liters),1unit Holding Tank, capacity(1500liters)",
    ],
    specifications: [
      " Total dissolved salt: > 95% Bacteria (CFU) & Endotoxins (EU): > 99%",
      "Water conversion factor: Max. 75%",
      "Water supply: Min. Input. L/m. (L/h): 20 (1200) Min. Input. Pressure KPa: 100",
      "Max. Input. Pressure KPa: 500",
      "Temperature: +5 C to +25 Quality: Potable water should be used. Additional pre- treatment is normally necessary. Membrane &machine life expectancy depends on inlet",
      "Quality: Potable water should be used. Additional pre- treatment is normally necessary. Membrane & machine life expectancy depends on inlet water quality.",
      "Fouling index (S.D.I): < 5 Drain requirement:Required capacity in L/m: Min. Input. L/m. (L/h): 20 (1200) Maximum flow occursduring flushing.",
      "Connection: Inlet: PVC union fit to pipe OD 25mm",
      "Drain: PVC union fit to pipe OD 32mm",
      "Outlet & return: PVC union fit to pipe OD 25mm",
    ],
  },
  {
    id: 2,
    image: "/images/product-images/Manual_Dialysis_Chair.jpg",
    description: "",
    brand: "",
    name: "Manual Dialysis Chair",
    category: "Hemodialysis",
    features: [
      "Economical and comfortable option for dialysis patients and caregivers.",
      "Barrier free accessibility from the side",
      "A fold downside tray,",
      "IV pole",
      "Reclining Trendelenburg positioning as well.",
      "Lockable casters",
      "Waterproof",
    ],
  },

  {
    id: 14,
    image: "/images/product-images/Drager-Primus_Anasthesia_machine.jpeg",
    description: "",
    brand: "",
    area: "featured",
    category: "ICU Equipment",
    name: "Refurbished Drager Primus Anasthesia Machine  ",
    features: [],
  },
  {
    id: 4,
    image: "/images/product-images/patient_monitor.jpg",
    description: "",
    brand: "PG S70 COUNTRY: ITALY",
    category: "ICU Equipment",
    area: "featured",
    name: "Patient Monitor",
    features: [
      "Pg S70 modular patient monitor complete",
      '15" LCD TFT touch screen.',
      "Resolution: 768x1024.",
      "Integrates module frame with 3 module slots.",
      "	5 Lead ECG, HR, RESP, NIBP, SPO2, PR,2-Temp Rechargeable Lithium Battery (11.1v/4000mah).",
    ],
  },
  {
    id: 5,
    image: "/images/product-images/Ventilator.png",
    description: "",
    brand: "PG VENT COUNTRY: ITALY",
    category: "ICU Equipment",
    name: "Ventilator ",
  },
  {
    id: 6,
    image: "/images/product-images/syringe_pump.png",
    description: "",
    brand: "",
    category: "Operating Theatre Equipment",
    name: "Syringe Pump",
    features: [
      "LCD TFT color display 4'3 touch screen",
      "Anti-reserve DERS (Drug Error Reduction System)",
      "Identify size for syringe of 5, 10, 20,30, 50/60 ml",
      "History records more than 5000 records",
      "Drug library: Up to 2000 drug names list and display",
      "Drug library: Up to 2000 drug names list and display",
      "DC 15V Lithium battery & power cable",
    ],
  },
  {
    id: 140,
    image: "/images/product-images/Drager-Primus_Anasthesia_machine.jpeg",
    description: "",
    brand: "",
    area: "featured",
    category: "Operating Theatre Equipment",
    name: "Refurbished Drager Primus Anasthesia Machine  ",
    features: [],
  },

  {
    id: 7,
    image: "/images/product-images/Infusion_pump.jpg",
    description: "",
    brand: "PG-807i",
    category: "ICU Equipment",
    name: "Infusion pump",
    features: [
      "LCD TFT color display 4.3” touch screen",
      "Anti-reserve DERS (Drug Error Reduction System)",
      "Nurse call RS232, data export, interface Mini USB",
      "History records more than 5000 records",
      "Drug library: Up to 2000 drug names list and display",
      "Drug library: Up to 2000 drug names list and display",
      "DC 15V Lithium battery & power cable",
    ],
  },
  {
    id: 8,
    image: "/images/product-images/ecg_machine.jpeg",
    description: "",
    brand: "",
    category: "Diagnostic Imaging Equipment",
    name: "ECG Machine",
    features: [
      "7 inch high resolution color touch screen.",
      "Full alphanumeric keyboard with shortcut keys, efficient in operation.",
      "Simultaneous 12 leads ECG acquisition and display.",
      "Automatic ECG measurements and interpretation.",
      "Internal storage up to 1000 cases, convenient for case review and statistic.",
      "Built-in rechargeable lithium high capacity battery.",
      "ECG data can be transmitted to PC via USB.",
      "ECG reports can be saved, opened, in PC via ECG playback software.",
    ],
  },
  {
    id: 8.5,
    image: "/images/product-images/Pulse_Oximeter.jpg",
    description: "",
    brand: "",
    category: "ICU Equipment",
    name: "Pulse Oximeter",
    features: [
      "Good accuracy with beep and alarm",
      "The Bright OLED Display Monitor.",
      "Innovative All Four Directions Display.",
      "Visual Alarm with Beep Sound.",
      "Perfusion Index (PI) Pulsatile Blood Flow.",
      "Measure Blood Oxygen Saturation SpO2 Level and Pulse Rate",
    ],
  },
  // {
  //   id: 9,
  //   image: "/images/product-images/Crash_Cart.jpg",
  //   description: "",
  //   brand:"",
  //   category: "Operating Theatre Equipment",
  //   name: "Crash Cart",
  //   features:["High-quality ABS Body with raised edge design.", "Stainless Steel Guard Rail.", "High quality Scratch- proof Aluminum Columns for extra strength.", "5 Drawers with Flexible & adjustable Inner partitions.", "2 Small Drawers", "2 Midsize Drawers", "1 Big Drawer", "Label card holders on drawers", "1 Defibrillator Shelf & 1 Extra Sliding Side Shelf.", "1 CPR Board, Oxygen Cylinder Holder.", "1 IV Pole, 1 Utility Container, 1 Sharp Container, 2 Dust Bins.", "Power Outlet & Hooks."]
  // },
  {
    id: 10,
    image: "/images/product-images/Defibrillators.png",
    description: "",
    brand: "",
    category: "ICU Equipment",
    name: "Defibrillator",
    features: [
      "Advanced solution for emergency medicine. Ergonomic form, extremely robust",
      "Close to the needs of the modern emergency medicine, rescue life guarantees impact-proof larger TFT",
      "LCD color 7” display",
      "powerful battery up to 5 hours continuous monitoring and different product configurations.",
      "Individuals can choose from basic to fully equipped models among the available optional: up to 12 leads ECG monitoring, AED & advisory working",
    ],
  },
  {
    id: 11,
    image: "/images/product-images/ICU_Bed.jpg",
    description: "",
    brand: "",
    category: "ICU Equipment",
    name: "ICU Bed",
  },

  {
    id: 12,
    image: "/images/product-images/renal_function_kit.jpeg",
    description: "",
    brand: "",
    area: "featured",
    category: "Hemodialysis",
    name: "Renal function kit",
    features: [],
  },
  {
    id: 13,
    image: "/images/product-images/surgical_light.png",
    description: "",
    brand: "PG EYES 505",
    category: "Operating Theatre Equipment",
    name: "Surgical Light ",
    features: [
      "Ceiling-mounted, double-dome, two 50cm domes, each luminance at least 120000 Lux (54 bulbs) (108 bulbs)",
    ],
  },
  {
    id: 16,
    image: "/images/product-images/Operation_Table.png",
    description: "",
    brand: "PG OTI-ONE",
    category: "Operating Theatre Equipment",
    name: "Operation Table ",
    features: [
      "Stainless steel structure with slow rebound latex foam mattress, five section body layout for multiple surgical position request, reliable 6- movements electrical controlling system with smooth movement & silent lifting, 350mm tabletop sliding applicable with both x ray and c-arm, individual kidney bridge elevation system and build-in backup battery.",
      "Mattress Pad 1 set",
      "Cable Controller 1 set",
      "Arm Support 1 pair",
      "Shoulder Support 1 pair",
      "Body Support 1 pair",
      "Leg Support 1 pair Anesthesia Frame 1 set",
    ],
  },
  {
    id: 17,
    image:
      "/images/product-images/Medical-Surgical-Portable-Suction-Machine.jpg",
    description: "",
    brand: "",
    category: "Operating Theatre Equipment",
    name: "Suction Machine",
    features: [
      "A high-capacity, compact suction machine for general surgical use. The NLS-MFB-( DJSM) features an oil-free, maintenance-free suction pump with 20 LPM capacity. Maximum negative pressure can be conveniently controlled from the regulator on the front panel. The durable, aesthetically designed body features a folding handle and is made from powder-coated metal and plastic. It comes with 2 glass jars, a footswitch, a tubing kit, and spare bacterial filters.",
      "Input Power: AC 220 V @ 50 Hz, 180 VA",
      "Pumping Capacity: 20 LPM",
      "Maximum Negative Pressure: 90 kPa",
      "Operating Noise: < 65 dB Jar Capacity: 2.5 L X 2",
    ],
  },
  {
    id: 18,
    image: "/images/product-images/breathing_circuit.png",
    description: "",
    brand: "",
    category: "ICU consumeables",
    name: "Breathing Circuit",
    features: [""],
  },

  {
    id: 19,
    image: "/images/product-images/Diathermy_Machine.jpg",
    description: "",
    brand: "",
    category: "Operating Theatre Equipment",
    name: "Diathermy Machine",
    features: [
      "Control and measurement front panel consists of two differently sloped areas, 130 ° sloped “measurement area” and 160 ° sloped 'control area', to provide operator great physical comfort when they setup or adjust power setting and observe the power measurement and neutral electrode's contact situation.",
      "Provide smoke evacuation that comes with heat- producing surgical methods (like electrosurgery or laser). Qualified for wide range of applications, from various open surgeries to minimal- access procedures, as well as under-water operation in gynecology and urology as measures the tissue resistance then automatically adjust power output under pre-set range, to optimize real cutting or coagulation performance",
      "Cutting mode: Pure, Blend 1- 3, Coagulation mode, Point, Soft, Bipolar",
      "Max. power output (watts): 50W-350W",
      "Load (ohms): 100-500",
      "Open circuit Vp-p: 1200v- 4600v Crest factor: 1.5-4.5",
    ],
  },
  {
    id: 20,
    image: "/images/product-images/Surgical_Sets.jpg",
    description: "",
    brand: " WINCOM COUNTRY: CHINA",
    category: "Operating Theatre Equipment",
    name: "Surgical Sets ",
  },
  {
    id: 21,
    image: "/images/product-images/Oxygen_cynlinder.jpg",
    description: "",
    brand: "WINCOM COUNTRY: CHINA",
    category: "ICU Equipment",
    name: "Oxygen cynlinder",
    features: [
      "Water Capacity(litres) - A type",
      "Usage - Medical Use",
      "Working Pressure - 200 kgf/cm2",
      "Type of cylinder - Filled",
      "Working Pressure - 150 kgf/cm2",
      "Cylinder Capacity - 30-150 kg",
      "Body Material - Aluminum",
      "Boiling Point - 250 bar tp",
      "Thickness - 3-4 mm",
    ],
  },

  {
    id: 23,
    image: "/images/product-images/Jay_5_Oxygen_Concentrator.jpg",
    description: "",
    brand: "",
    category: "ICU Equipment",
    name: "Jay 5 Oxygen Concentrator",
    features: [
      "PSA (Pressure Swing Absorption) technology",
      "Adjustable flow rate",
      "Large LCD display for: accumulating timing",
      "Present timing from:10min to 40 hrs.",
      "Digital: Pressure digital; Temperature digital",
      "Purity digital",
      "Maintenance reminding",
    ],
  },
  {
    id: 24,
    image: "/images/product-images/Fully_Automated_Dialysis_Couch.jpg",
    description: "",
    brand: "",
    category: "Hemodialysis",
    name: "Fully Automated Dialysis Couch",
    features: [
      "Estimated lead time: 40 days",
      "European 4 sections ergonomics design",
      "Baosteel from Fortune Global 500",
      "Environmental plastic can be sterilized in 100°C, tensile up to 30MPa",
      "Panasonic Robotic ensure",
      "360° full smooth welding",
    ],
  },

  // {
  //   id: 25,
  //   image: "/images/product-images/Dialyzer.jpg",
  //   description: "",
  //   brand:"",
  //   category: "Medical Consumeables",
  //   name: "Dialyzer",
  //   features:["1.8M2 Highflux dialyzer.", "Polyethersulfone  Membrane", "Asymmetric membrane structure provides a unique barrier that absorbs endotoxins.", "Other advances in fiber and dialyzer technology enable more disruptive flow to improve solute removal.", "The resulting steeper sieving curve enhances small and middle molecule clearance without increasing albumin loss.", "   Convenience for use in the arterial end upright or arterial inverted position"]
  // },
  {
    id: 36,
    image: "/images/product-images/Dialyzer.jpg",
    description: "",
    brand: "",
    category: "hemodialysis consumeables",
    name: "Dialyzer",
    features: [
      "1.8M2 Highflux dialyzer.",
      "Polyethersulfone  Membrane",
      "Asymmetric membrane structure provides a unique barrier that absorbs endotoxins.",
      "Other advances in fiber and dialyzer technology enable more disruptive flow to improve solute removal.",
      "The resulting steeper sieving curve enhances small and middle molecule clearance without increasing albumin loss.",
      "   Convenience for use in the arterial end upright or arterial inverted position",
    ],
  },
  {
    id: 260,
    image: "/images/product-images/bloodline.jpg",
    description: "",
    brand: "",
    category: "hemodialysis consumeables",
    name: "Bloodline",
    features: [
      "Comes with waste bag.",
      "Perfect Medical produces dialysis blood line tubing set consist of arterial and venous lines, used during dialysis and are attached with A.V.fistula and dialyzer.",
      "Arterial blood tubing: the portion of the tubing set that transports blood from the patient to the hemodialyzer inlet port.",
      "Venous blood tubing: the portion of the tubing set transports blood from the hemodialyzer outlet.",
      "Port back to the patient.",
      "Medical grade PVC Tubing.",
      "Pump Segment for Conventional and high flow rates",
    ],
  },
  {
    id: 26,
    image: "/images/product-images/x-ray.jpeg",
    description: "",
    area: "featured",
    brand: "",
    category: "Diagnostic Imaging Equipment",
    name: "Radiography X-ray Machine",
    features: [],
  },
  {
    id: 27,
    image: "/images/product-images/ultrasound.jpeg",
    description: "",
    brand: "",
    area: "featured",
    category: "Diagnostic Imaging Equipment",
    name: "Ultrasound",
    features: [
      "Three probes: Convex, linear, and transvaginal",
      "4D ultrasound Innovative RF Platform User-defined Protocols",
      "Smart Measurements",
      "Auto IMT",
      "Auto Trace in PW/CW Mode",
      "Preview allows extended view of the relationship of anatomical structures",
      "Value-Added 4D Performance",
      "Flexible Display Format",
      "15-inch high-resolution LCD monitor that rotates a full 180 degrees for enhanced ergonomics.",
      "8-inch touch screen panel reduces physical strain.",
      "Compact transducer connector for easy access",
      "High quality processors for enhanced powerful performance.",
      "Total Connectivity",
    ],
  },
  {
    id: 28,
    image: "/images/product-images/Bicarbonate_Cartridge.jpg",
    description: "",
    brand: "",
    category: "hemodialysis consumeables",
    name: "Bicarbonate Cartridge",
    features: [
      "650g Bicarbonate cartridge",
      "No risk of contamination and bacterial growth.",
      "Lighter and smaller container, removing strain to dissolve and handle heavy cans.",
      "Cap closure for cleaner posttreatment environment.",
      "	Less storage space required.",
      "Mercury reservoir with isolation valve",
      "Steel hinge pivots",
      "Range 0-300mmH",
      "Supplied with adult size cuff & latex free bulb",
    ],
  },
  {
    id: 29,
    image: "/images/product-images/Femoral_Catheter_(Single_Lumen).jpg",
    description: "",
    brand: "",
    category: "hemodialysis consumeables",
    name: "Femoral Catheter (Single Lumen)",
    features: [
      "Soft tip.",
      "Small rotating fixation wing.",
      "Extension lines stand repeated clamping and declamping.",
      "Multiple threads female luer end.",
      "Injection caps.",
      "Variety of sizes, lengths, and shapes",
    ],
  },
  // {
  //   id: 30,
  //   image: "/images/product-images/Guide_Wire.jpg",
  //   description: "",
  //   brand:"",
  //   category: "Medical Consumeables",
  //   name: "Guide Wire",
  //   features:["Material: Nitinol Core (Surface PTFE heat shrinking tube).", "Dimension: 032/035/038", "Length: 80cm/120cm/150cm/1 60cm/180cm/ 260cm", "Spring Length: 3cm/4cm/5cm Tip"]

  // },
  {
    id: 31,
    image: "/images/product-images/Fistula_Needle.jpg",
    description: "",
    brand: "",
    category: "hemodialysis consumeables",
    name: "Fistula Needle",
    features: [
      "Integrated safety device",
      "Effective protection against Needle Stick Injury",
      "Ultra-siliconized thin walled sharp needle with beveled back eye for easy insertion and minimize trauma to the patient",
      "Soft and kink resistant medical grade PVC tubing",
      "Available with color coded fixed & rotating wings",
    ],
  },
  {
    id: 32,
    image: "/images/product-images/acid_concentrate.jpeg",
    description: "",
    brand: "",
    category: "hemodialysis consumeables",
    name: "Acid Concentrate (10L)",
    features: [
      "10L Acidic hemodialysis concentrates",
      "Sodium	138	mmol/l",
      "Potassium	2	mmol/l",
      "Calcium	1.5	mmol/l",
      "Magnesium 1	mmol/l",
      "Bicarbonate 35	mmol/l",
      "Acetate	3	mmol/l",
    ],
  },

  {
    id: 37,
    image: "/images/product-images/blue_gate.png",
    description: "",
    brand: "",
    category: "Hemodialysis",
    name: "Blue gate UPS(3.0KV A)",
    features: [
      "Phase: Single phase with ground",
      "Capacity (VA/Watts):3000va/2700W.",
      "Nominal Voltage: 200/208/2220/230/240 VAC",
      "Mode: AC",
      "Operating frequency range: 40- 70Hz",
      "Battery type (Units)=12V/9AH (6 units)",
      "Typical Recharge Time:4H to recover capacity.",
    ],
  },
  {
    id: 130,
    image: "/images/product-images/motuary_freezer.jpeg",
    description: "",
    brand: "",
    category: "Morgue and Body handling",
    name: "Mortuary Freezer",
    features: [
      "The whole refrigerator is made of stainless steel, which is used to store the corpse.",
      "The insulation layer is made of polyurethane foaming machine to accurately control the foaming density.",
      "Built-in evaporator, pure copper tube, refrigeration effect is more significant",
      "Equipped with an independent and complete refrigeration system, composed of single machine and single cycle refriger- ation system.",
      "High precision temperature control, three digit high brightness digital display, easy to observe the temperature in the box.",
      "All doors have safety lock design to prevent arbitrary opening.",
      "Stainless steel body tray with handle is placed on the roller track for easy entry and exit.",
      "Freezing temperature according to customer requirements, and the temperature of each cabinet does not affect each other.",
      "High efficiency and environmental protection compressor, environmental protection fluorine-free refrigeration system.",
      "The equipment has sound buzzer alarm and light flashing alarm",
      "Keyboard lock, password protection function, prevent arbitrary adjustment of operating parameters.",
    ],
  },
  {
    id: 131,
    image: "/images/product-images/motuary_body_tray.jpeg",
    description: "",
    brand: "",
    category: "Morgue and Body handling",
    name: "Mortuary Body Tray",
    features: [
      "stainless steel structure designed to hold, store and transport the bodies of the deceased.",
      "They come with big handles for ease of operation and ergonomics.",
      "The seamless design limits the potential for debris buildup that could lead to contamination. 3. Smooth inner Angle, with drainage hole, easy to clean",
    ],
  },
  {
    id: 132,
    image: "/images/product-images/embalming_table.jpeg",
    description: "",
    brand: "",
    category: "Morgue and Body handling",
    name: "Embalming Table",
    features: [
      "Stainless steel top with extra deep trough for easy flow of fluids.",
      "It is equipped with 4 quality universal wheels to ensure easy movement of the device.",
      "The drain, located in the center of the foot end, quickly eliminates fluid from the table.",
      "Each end can be adjusted independently according to individual working height and displacement.",
      "Ideal for anticorrosion and transfer.",
    ],
  },
  {
    id: 133,
    image: "/images/product-images/embalming-table-with-cover.jpeg",
    description: "",
    brand: "",
    category: "Morgue and Body handling",
    name: "Embalming Table with cover",
    features: [
      "Made of high quality 304 stainless steel, welding through the quality assurance.",
      "Hinged lid with swinging latch, camouflage helps prevent discomfort with other patients and visitors.",
      "Four casters with brakes, easy to operate and safe to place.",
      "Tables have ramps to drain water to one end and into an optional bucket row that hangs neatly under the frame.",
      "The PVC stop valve is located below the drain pipe and is used to stop the flow of fluid while the barrel is being emptied. ",
      "Ideal for discreet observation in laboratories and all mortuary facilities.",
    ],
  },
  {
    id: 134,
    image: "/images/product-images/autopsy_table.jpeg",
    description: "",
    brand: "",
    category: "Morgue and Body handling",
    name: "Autopsy Table",
    features: [
      ".The table is equipped with movable sieve partition and the side cabinet is equipped with drawers for placing instruments",
      "The louver outlet on the ruler table can quickly purify the air. It needs to be connected with the external extraction fan",
      "The sink is equipped with a hair isolator to prevent the hair from getting into the drainage pipe and blocking",
      "The pulverizer under the pool can crush the dissected tissue and discharge it through the drainage outlet (optional)",
      "Table around arc structure, not easy to scale, easy to clean, luxurious and beautiful",
      "Equipped with cold and heat regulator, manual faucet and hose (connected to water heater)",
      "Nine multi-functional mobile spray rinsing guns can rinse the overall dirt of the dissection table ",
      "There are five flushes on the side of the table to wash the dirt during the dissection",
      "The upper part of the LED light, hook, ULTRAVIOLET disinfection lamp",
      "The side of the platform has leakage protection device, waterproof socket 220v. 50HZ 11.Stainless steel autopsy cart (optional)",
    ],
  },
];

export const partners = [
  { id: 1, image: "/images/partners/partner1.jpeg" },
  { id: 2, image: "/images/partners/partner2.jpeg" },
  { id: 3, image: "/images/partners/partner3.jpeg" },
  { id: 4, image: "/images/partners/partner4.jpeg" },
  { id: 5, image: "/images/partners/partner5.jpeg" },
  { id: 6, image: "/images/partners/partner6.jpeg" },
  { id: 7, image: "/images/partners/partner7.jpeg" },
  { id: 8, image: "/images/partners/partner8.jpeg" },
  { id: 9, image: "/images/partners/partner9.jpeg" },
  { id: 10, image: "/images/partners/partner10.jpeg" },
];

export default data;
